/*
  Manual edit on top of Prisma's auto-generated migration:

  Prisma's default would DROP COLUMN "id" and re-ADD it as UUID NOT NULL,
  which loses all existing user rows. The values currently stored in
  users.id are already UUID strings (generated by Prisma's @default(uuid())),
  so the safe path is a CAST in place.

  This is the same migration Prisma would generate if the source column were
  already uuid — same end state, just non-destructive.
*/

-- AlterTable: cast users.id from text to uuid in place, preserving values.
ALTER TABLE "users" ALTER COLUMN "id" TYPE UUID USING "id"::UUID;

-- AlterTable: timestamps become timestamptz(6) (existing values are timezone-naive).
ALTER TABLE "users" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(6) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "users" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(6) USING "updatedAt" AT TIME ZONE 'UTC';

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "jti" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "familyId" UUID NOT NULL,
    "isUsed" BOOLEAN NOT NULL DEFAULT false,
    "isRevoked" BOOLEAN NOT NULL DEFAULT false,
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userAgent" VARCHAR(255),
    "ipAddress" VARCHAR(45),

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("jti")
);

-- CreateIndex
CREATE INDEX "refresh_tokens_userId_familyId_idx" ON "refresh_tokens"("userId", "familyId");

-- CreateIndex
CREATE INDEX "refresh_tokens_expiresAt_idx" ON "refresh_tokens"("expiresAt");

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
